version: "3.7"
services:

  lvs:
    image: haproxy:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/local/etc/haproxy/
    command: haproxy -f /usr/local/etc/haproxy/haproxy.cfg

  master_kvs:
    image: redis:alpine
    ports:
      - "6379"

  slave_kvs:
    image: redis:alpine
    ports:
      - "6380:6379"

  queue-1:
    image: spotify/kafka
    ports:
      - "9092"

  queue-2:
    image: spotify/kafka
    ports:
      - "9093:9092"

  dummy_1:
    image: nginx

  dummy_2:
    image: nginx
