version: "3.7"
services:
  lvs:
    image: haproxy:latest
    ports:
      - "8080:80"
    volumes:
      - ./lvs/config/:/usr/local/etc/haproxy/
    command: haproxy -f /usr/local/etc/haproxy/haproxy.cfg

  master_kvs:
    image: eqalpha/keydb
    ports:
      - "6379:6379"

  slave_kvs:
    image: eqalpha/keydb
    ports:
      - "6380:6379"

  queue_primary:
    image: eqalpha/keydb
    ports:
      - "63790:6379"

  queue_secondary:
    image: eqalpha/keydb
    ports:
      - "63791:6379"

  dummy_1:
    image: nginx
    ports:
      - "8888:80"

  dummy_2:
    image: nginx
    ports:
      - "8800:80"
